In [2]:
import numpy as np 
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
training_data, testing_data = keras.datasets.cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 953s 6us/step


In [6]:
X_train, y_train = training_data
X_test, y_test = testing_data


In [14]:
X_train.shape
y_train.shape

y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [27]:
X_train, X_test = X_train/255.0, X_test/255.0
X_train

array([[[[1.39537613e-08, 1.46632746e-08, 1.48997790e-08],
         [1.01696904e-08, 1.08792037e-08, 1.06426993e-08],
         [1.18252215e-08, 1.13522126e-08, 1.01696904e-08],
         ...,
         [3.73676998e-08, 3.12185846e-08, 2.55424783e-08],
         [3.59486732e-08, 2.95630536e-08, 2.41234518e-08],
         [3.50026555e-08, 2.93265492e-08, 2.43599562e-08]],

        [[3.78407087e-09, 4.73008858e-09, 4.73008858e-09],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [4.25707972e-09, 1.89203543e-09, 0.00000000e+00],
         ...,
         [2.90900448e-08, 2.08123898e-08, 1.30077436e-08],
         [2.81440271e-08, 1.96298676e-08, 1.18252215e-08],
         [2.88535403e-08, 2.05758853e-08, 1.34807525e-08]],

        [[5.91261073e-09, 5.67610630e-09, 4.96659301e-09],
         [3.78407087e-09, 1.65553100e-09, 0.00000000e+00],
         [1.15887170e-08, 6.38561958e-09, 1.89203543e-09],
         ...,
         [2.79075226e-08, 1.98663720e-08, 1.18252215e-08],
         [

In [28]:
X_train

array([[[[1.39537613e-08, 1.46632746e-08, 1.48997790e-08],
         [1.01696904e-08, 1.08792037e-08, 1.06426993e-08],
         [1.18252215e-08, 1.13522126e-08, 1.01696904e-08],
         ...,
         [3.73676998e-08, 3.12185846e-08, 2.55424783e-08],
         [3.59486732e-08, 2.95630536e-08, 2.41234518e-08],
         [3.50026555e-08, 2.93265492e-08, 2.43599562e-08]],

        [[3.78407087e-09, 4.73008858e-09, 4.73008858e-09],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [4.25707972e-09, 1.89203543e-09, 0.00000000e+00],
         ...,
         [2.90900448e-08, 2.08123898e-08, 1.30077436e-08],
         [2.81440271e-08, 1.96298676e-08, 1.18252215e-08],
         [2.88535403e-08, 2.05758853e-08, 1.34807525e-08]],

        [[5.91261073e-09, 5.67610630e-09, 4.96659301e-09],
         [3.78407087e-09, 1.65553100e-09, 0.00000000e+00],
         [1.15887170e-08, 6.38561958e-09, 1.89203543e-09],
         ...,
         [2.79075226e-08, 1.98663720e-08, 1.18252215e-08],
         [

In [19]:
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)


In [20]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [29]:
model = keras.Sequential(
    [
        layers.Conv2D(32, (3,3), activation='relu', input_shape=(32, 32, 3)),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64, (3,3), activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64, (3,3), activation='relu'),
        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dense(10, activation='softmax')
    ]
)

model.compile(
    optimizer='adam',
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(X_train, y_train, epochs=30, validation_data=(X_test, y_test))

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Teast Accuracy: {test_acc:2f}')

/Users/alert/deepLearning/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 53s 31ms/step - accuracy: 0.0978 - loss: 2.3029 - val_accuracy: 0.1000 - val_loss: 2.3026
Epoch 2/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 47s 30ms/step - accuracy: 0.0999 - loss: 2.3028 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 3/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 47s 30ms/step - accuracy: 0.0985 - loss: 2.3029 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 4/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 49s 31ms/step - accuracy: 0.0974 - loss: 2.3028 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 5/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 43s 27ms/step - accuracy: 0.0989 - loss: 2.3028 - val_accuracy: 0.1000 - val_loss: 2.3026
Epoch 6/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 43s 27ms/step - accuracy: 0.0998 - loss: 2.3028 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 7/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 44s 28ms/step - accuracy: 0.0982 - loss: 2.3028 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 8/30
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 52s 33ms/step - accuracy: 0.0988 -

In [ ]:
y_train

(50000, 10)

In [25]:
X_test

array([[[[2.42983468e-03, 1.72241446e-03, 7.53556324e-04],
         [2.44521338e-03, 1.70703576e-03, 7.22798923e-04],
         [2.53748558e-03, 1.78392926e-03, 7.84313725e-04],
         ...,
         [2.10688197e-03, 1.46097655e-03, 5.53633218e-04],
         [1.93771626e-03, 1.39946175e-03, 5.53633218e-04],
         [1.78392926e-03, 1.30718954e-03, 5.07497116e-04]],

        [[2.33756248e-03, 1.72241446e-03, 7.84313725e-04],
         [2.32218378e-03, 1.69165705e-03, 6.15148020e-04],
         [2.44521338e-03, 1.75317186e-03, 6.92041522e-04],
         ...,
         [2.09150327e-03, 1.46097655e-03, 4.76739715e-04],
         [1.92233756e-03, 1.39946175e-03, 4.92118416e-04],
         [1.83006536e-03, 1.35332564e-03, 5.22875817e-04]],

        [[2.32218378e-03, 1.69165705e-03, 7.22798923e-04],
         [2.32218378e-03, 1.67627835e-03, 5.07497116e-04],
         [2.42983468e-03, 1.70703576e-03, 5.53633218e-04],
         ...,
         [2.13763937e-03, 1.50711265e-03, 5.22875817e-04],
         [

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 7us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 326s 12us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 25s 6us/step


/Users/alert/deepLearning/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_3 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266,610 (1.02 MB)

 Trainable params: 266,610 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

In [65]:
(X_train_new, y_train_new), (X_test_new, y_test_new) = fashion_mnist.load_data()

X_validation, X_main_train = X_train_new[:5000] / 255.0, X_train_new[5000:] / 255.0
y_validation, y_main_train = y_train_new[:5000], y_train_new[5000:]


fashion_model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dense(300, activation="relu"),
    keras.layers.Dense(100, activation="relu"),
    keras.layers.Dense(10, activation='softmax')
])

fashion_model.summary()

print(X_test_new.shape)

/Users/alert/deepLearning/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_13 (Flatten)            │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266,610 (1.02 MB)

 Trainable params: 266,610 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

(10000, 28, 28)


In [32]:
fashion_model.layers

[<Flatten name=flatten_4, built=True>,
 <Dense name=dense_9, built=True>,
 <Dense name=dense_10, built=True>,
 <Dense name=dense_11, built=True>]

In [38]:
x, y = fashion_model.layers[2].get_weights()
x.shape

(300, 100)

In [58]:
fashion_model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="sgd",
    metrics=["accuracy"]
)

fashion_model.fit(X_main_train, y_main_train, epochs=7, validation_data=(X_validation, y_validation))

Epoch 1/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.7541 - loss: 0.7214 - val_accuracy: 0.8018 - val_loss: 0.5620
Epoch 2/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8203 - loss: 0.5132 - val_accuracy: 0.8384 - val_loss: 0.4767
Epoch 3/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.8332 - loss: 0.4770 - val_accuracy: 0.8506 - val_loss: 0.4447
Epoch 4/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8409 - loss: 0.4571 - val_accuracy: 0.8482 - val_loss: 0.4385
Epoch 5/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8451 - loss: 0.4455 - val_accuracy: 0.8442 - val_loss: 0.4528
Epoch 6/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8482 - loss: 0.4385 - val_accuracy: 0.8310 - val_loss: 0.4743
Epoch 7/7
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8496 - loss: 0.4334 - val_accuracy: 0.8472 - val_loss: 0.4399


In [59]:
fashion_model.evaluate(X_test_new/255.0, y_test_new)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8298 - loss: 0.4787


[0.4787062108516693, 0.829800009727478]

In [68]:
second_fashion_model = keras.Sequential(
    [
        layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
        layers.MaxPooling2D(2, 2),
        layers.Conv2D(64, (3, 3), activation="relu"),
        layers.MaxPooling2D(2, 2), 
        layers.Flatten(),
        layers.Dense(128, activation="relu"),
        layers.Dense(10, activation="softmax")
    ]
)

second_fashion_model.compile(
    optimizer='sgd',
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)


/Users/alert/deepLearning/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
second_fashion_model.fit(X_main_train, y_main_train, epochs=10, validation_data=(X_validation, y_validation))

Epoch 1/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8634 - loss: 0.3844